=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/DTD/po.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT quantity (#PCDATA) >
<!ELEMENT ItemCode (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT state (#PCDATA) >
<!ELEMENT zip (#PCDATA) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT addrLine2 (#PCDATA) >
<!ELEMENT addrLine1 (#PCDATA) >
<!ELEMENT shipping-address (addrLine1,addrLine2,city,state,zip,country) >
<!ELEMENT item (ItemCode,quantity) >
<!ELEMENT orderItems (item+) >
<!ELEMENT purchaseOrder (orderItems,shipping-address+) >

=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/DTD/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE purchaseOrder SYSTEM "C:\NIT\Webservices\DTD\po.dtd">
<purchaseOrder>
	<orderItems>
		<item>
			<ItemCode>IC201</ItemCode>
			<quantity>xyx</quantity>
		</item>
		<item>
			<ItemCode>IC202</ItemCode>
			<quantity>20</quantity>
		</item>
	</orderItems>
	<shipping-address>
		<addrLine1>S.RNagar</addrLine1>
		<addrLine2>CDAC</addrLine2>
		<city>hyd</city>
		<state>TG</state>
		<zip>50031</zip>
		<country>India</country>
	</shipping-address>
</purchaseOrder>
