=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/XSD/book-type1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="book" type="BookType"/>
	
	<xs:complexType name="BookType">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="id" type="xs:int"/>
			<xs:element name="author" type="AuthorType"/>
			<xs:element name="publisher" type="PublisherType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="PublisherType">
		<xs:sequence>
			<xs:element name="publisherName" type="xs:string"/>
			<xs:element name="established-year" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AuthorType">
		<xs:sequence>
			<xs:element name="dob" type="xs:date"/>
			<xs:element name="authorName" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/XSD/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/NIT/Webservices/book-type1.xsd">
	<title>XML &amp; Webservices</title>
	<id>101</id>
	<author>
		<dob>1991-05-20</dob>
		<authorName>Ashok Bollepalli</authorName>
	</author>
	<publisher>
		<publisherName>Midhuna Xerox Centre</publisherName>
		<established-year>2010</established-year>
	</publisher>
</book>
