=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/XSD/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="purchaseOrder" type="purchaseOrderType"/>
	
	<xs:complexType name="purchaseOrderType">
		<xs:sequence>
			<xs:element name="orderItems" type="OrderItemsType"/>
			<xs:element name="shipping-address" type="ShippingAddrType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ShippingAddrType">
		<xs:sequence>
			<xs:element name="addrLine1" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:int"/>
			<xs:element name="country" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="OrderItemsType">
		<xs:sequence>
			<xs:element name="item" type="ItemType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="ItemCode" type="xs:string"/>
			<xs:element name="quantity" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/XSD/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/NIT/Webservices/XSD/po.xsd">
	<orderItems>
		<item>
			<ItemCode>IC001</ItemCode>
			<quantity>10</quantity>
		</item>
	</orderItems>
	<shipping-address>
		<addrLine1>Hyd</addrLine1>
		<city>hyd</city>
		<state>TG</state>
		<zip>50081</zip>
		<country>India</country>
	</shipping-address>
</purchaseOrder>
