=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/XSD-Namespaces/stock.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://vishkasteel.in/product/retail" xmlns:vpr="http://vishkasteel.in/product/retail" elementFormDefault="qualified">
	<xs:element name="stockMarket" type="vpr:stockMarketType"/>
	<xs:complexType name="stockMarketType">
		<xs:sequence>
			<xs:element name="buyStock" type="vpr:buyStockType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="buyStockType">
		<xs:sequence>
			<xs:element name="stock" type="vpr:stockType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="transactionInfo" type="vpr:overseasTransactionInfoType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="stockType">
		<xs:sequence>
			<xs:element name="stockQuote" type="xs:string"/>
			<xs:element name="units" type="xs:int"/>
			<xs:element name="price" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="transactionInfoType">
		<xs:sequence>
			<xs:element name="marketType" type="xs:string"/>
			<xs:element name="orderDate" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="overseasTransactionInfoType">
		<xs:complexContent>
			<xs:extension base="vpr:transactionInfoType">
				<xs:sequence>
					<xs:element name="place" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== dhirajhargode/java-practice/AShok sir class room example/Sample_XML_DTD_XSD/XSD-Namespaces/stock.xml
<?xml version="1.0" encoding="UTF-8"?>
<vs:stockMarket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://vishkasteel.in/product/retail file:///C:/Workshop/Trainings/WebServices/stock.xsd" xmlns:vs="http://vishkasteel.in/product/retail">
	<vs:buyStock>
		<vs:stock>
			<vs:stockQuote>CIPLA</vs:stockQuote>
			<vs:units>10</vs:units>
			<vs:price>100</vs:price>
		</vs:stock>
		<vs:transactionInfo>
			<vs:marketType>BSE</vs:marketType>
			<vs:orderDate>2013-10-03</vs:orderDate>
			<vs:place>US</vs:place>
		</vs:transactionInfo>
	</vs:buyStock>
</vs:stockMarket>
